CV_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from CV_project import settings
from app_resume.views import MainView

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('users/', include('app_users.urls')),
    path('resume/', include('app_resume.urls')),
    path('social/', include('app_social.urls')),
    path('job_hunt', include('app_job_hunt.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_users/urls.py
from django.urls import path

from .views import ProfileView, SignUpView, CreateProfileView, Login, Logout, \
    ProfileUpdateView, UserUpdateView, SocialLinksUpdateView

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('user_update/', UserUpdateView.as_view(), name='user_update'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('create_profile/', CreateProfileView.as_view(), name='create_profile'),
    path('profile_update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('social_links_update/', SocialLinksUpdateView.as_view(), name='social_links_update')
]

app_resume/models.py
import uuid

from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.db import models

from app_resume.validators import percentage_validator


class RepresentationForResumesObjectMixin:
    def __str__(self):
        return f'{type(self).__name__} object for {self.resume.position}' \
               f' resume by {self.resume.user.username}'


# Create your models here.
class Resume(models.Model):
    profile = models.ForeignKey('app_users.Profile', on_delete=models.CASCADE, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    slug = AutoSlugField(populate_from='position', unique_with='user')
    position = models.CharField(max_length=150)
    about_me = models.TextField(blank=True, null=True)
    soft_skills = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    is_primary = models.BooleanField(default=False)
    rating = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.is_primary:
            try:
                temp = Resume.objects.get(is_primary=True, user=self.user)
                if self != temp:
                    temp.is_primary = False
                    temp.save()
            except Resume.DoesNotExist:
                pass
        super(Resume, self).save(*args, **kwargs)

    def __str__(self):
        return f'Resume object for {self.position} position by {self.user.username}'


class MainEducation(RepresentationForResumesObjectMixin, models.Model):
    EDUCATION_LEVELS = [
        ('Basic General', 'Основное общее образование'),
        ('Secondary General', 'Cреднее (полное) общее образование'),
        ('Vocational education', 'Cреднее профессиональное образование'),
        ('Higher education', 'Высшее образование'),
    ]

    DEGREES = [
        ('Other', 'Другое'),
        ('Bachelor', 'Бакалавр'),
        ('Specialist', 'Специалист'),
        ('Master', 'Магистр'),
    ]

    resume = models.OneToOneField('Resume', on_delete=models.CASCADE, editable=False)

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    level = models.CharField(max_length=25, choices=EDUCATION_LEVELS, default='Basic General')
    degree = models.CharField(max_length=10, choices=DEGREES, blank=True, null=True)

    def get_level(self):
        return dict(self.EDUCATION_LEVELS).get(self.level)

    def get_degree(self):
        return dict(self.DEGREES).get(self.degree)


class Institution(RepresentationForResumesObjectMixin, models.Model):
    main_education = models.ForeignKey('MainEducation', on_delete=models.CASCADE, editable=False)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, editable=False)

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    title = models.CharField(max_length=150, blank=True, null=False, default='New Object')
    description = models.TextField(blank=True, null=True)
    website_url = models.URLField(blank=True, null=True)
    diploma = models.FileField(upload_to='files/main_diplomas/', blank=True, null=True)
    completion_date = models.DateField(blank=True, null=True)
    is_primary = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.is_primary:
            try:
                temp = Institution.objects.get(is_primary=True, resume=self.resume)
                if self != temp:
                    temp.is_primary = False
                    temp.save()
            except Institution.DoesNotExist:
                pass
        super().save(*args, **kwargs)


class AdditionalEducation(RepresentationForResumesObjectMixin, models.Model):
    resume = models.ForeignKey('Resume', on_delete=models.CASCADE, editable=False)

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    title = models.CharField(max_length=150, blank=True, null=False, default='New Object')
    description = models.TextField(blank=True, null=True)
    website_url = models.URLField(blank=True, null=True)
    diploma = models.FileField(upload_to='files/additional_diplomas/', blank=True, null=True)
    completion_date = models.DateField(blank=True, null=True)


class ElectronicCertificate(RepresentationForResumesObjectMixin, models.Model):
    resume = models.ForeignKey('Resume', on_delete=models.CASCADE, editable=False)

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    slug = AutoSlugField(populate_from='title', unique_with='resume')
    title = models.CharField(max_length=150, blank=True, null=False, default='New Object')
    certificate_url = models.URLField(blank=True, null=True)
    certificate = models.FileField(upload_to='files/certificates/', blank=True, null=True)
    completion_percentage = models.IntegerField(blank=True, null=True, validators=[percentage_validator])
    completion_date = models.DateField(blank=True, null=True)


class Skill(RepresentationForResumesObjectMixin, models.Model):
    resume = models.ForeignKey('Resume', on_delete=models.CASCADE, editable=False)

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    title = models.CharField(max_length=45)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


class WorkExpSection(RepresentationForResumesObjectMixin, models.Model):
    resume = models.ForeignKey('Resume', on_delete=models.CASCADE, editable=False)

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    title = models.CharField(max_length=150, blank=True, null=False, default='New Object')
    start_date = models.DateField(blank=True, null=True)
    finish_date = models.DateField(blank=True, null=True)


class Job(models.Model):
    work_exp_section = models.ForeignKey('WorkExpSection', on_delete=models.CASCADE, editable=False)

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    title = models.CharField(max_length=150, blank=True, null=False, default='New Object')
    description = models.TextField(blank=True, null=True)
    project_url = models.URLField(blank=True, null=True)
    git_url = models.URLField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    finish_date = models.DateField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    position = models.CharField(max_length=150, blank=True, null=True)
    company = models.CharField(max_length=150, blank=True, null=True)
    company_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return f'{type(self).__name__} object for {self.work_exp_section.resume.position}' \
               f' resume by {self.work_exp_section.resume.user.username}'

app_users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver

from app_social.model_mixins import CompressImageBeforeSaveMixin
from app_users.validators import phone_number_validator


# Create your models here.
class Profile(CompressImageBeforeSaveMixin, models.Model):
    def __init__(self, *args, **kwargs):
        self.image_width = 250
        self.image_name_suffix = 'user_image'
        super().__init__(*args, **kwargs)

    GENDERS = [
        ('M', 'Муж'),
        ('F', 'Жен'),
        ('O', 'Другой'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, editable=False)

    birthday_date = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=6, blank=True, null=True, choices=GENDERS)
    phone_number = models.CharField(max_length=15, blank=True, null=True, validators=[phone_number_validator,])
    image = models.ImageField(upload_to='avatars/', blank=True, null=True)

    def get_gender(self):
        return dict(self.GENDERS).get(self.gender)

    def __str__(self):
        return f'{self.user.username}`s Profile object'

    def delete(self, *args, **kwargs):
        self.image.delete(save=False)
        super().delete(*args, **kwargs)


class SocialLinks(models.Model):
    profile = models.OneToOneField('Profile', on_delete=models.CASCADE, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, editable=False)

    twitter = models.URLField(blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    linked_in = models.URLField(blank=True, null=True)
    vk = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    hh = models.URLField(blank=True, null=True)
    git_hub = models.URLField(blank=True, null=True)

    class Meta:
        verbose_name = "Social Links"
        verbose_name_plural = "Social Links"

    def __str__(self):
        return f'{self.user.username}`s SocialLinks object'

app_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User

import app_resume.models
from .models import Profile, SocialLinks

from django.utils.translation import gettext_lazy as _


class SignUpUserForm(UserCreationForm):
    username = forms.CharField(
        label='Логин для входа:',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'aria-describedby': "usernameHelp",
                                      }))

    email = forms.EmailField(
        label='Email:',
        widget=forms.EmailInput(attrs={'class': 'form-control',
                                       'aria-describedby': "emailHelp",
                                       }))

    password1 = forms.CharField(
        label='Пароль:',
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'id': 'password1_field'}))

    password2 = forms.CharField(
        label='Повторите пароль:',
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'id': 'password2_field'}))

    first_name = forms.CharField(
        label='Имя:',
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'area-describedby': 'first_nameHelp',
                                      }))

    last_name = forms.CharField(
        label='Фамилия:',
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'area-describedby': 'last_nameHelp',
                                      }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(
        label='Имя пользователя:',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'area-describedby': 'usernameHelp',
                                      }))

    first_name = forms.CharField(
        label='Имя:',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'area-describedby': 'first_nameHelp',
                                      }))

    last_name = forms.CharField(
        label='Фамилия:',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'area-describedby': 'last_nameHelp',
                                      }))

    email = forms.EmailField(
        label='Адрес электронной почты:',
        widget=forms.EmailInput(attrs={'class': 'form-control',
                                       'area-describedby': 'last_nameHelp',
                                       }))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class CreateProfileForm(forms.ModelForm):
    GENDER_CHOICES = (
        ('M', 'Муж'),
        ('F', 'Жен'),
        ('O', 'Другое'),
    )

    birthday_date = forms.DateField(
        label='День вашего рождения:',
        widget=forms.DateInput(attrs={'class': 'form-control',
                                      'type': 'date'}),
        required=False
    )

    gender = forms.CharField(
        label='Пол:',
        widget=forms.Select(attrs={'class': 'form-control'},
                            choices=GENDER_CHOICES),
        required=False
    )

    phone_number = forms.CharField(
        label='Телефон:',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'value': '+7',
                                      'placeholder': '+7'}),
        required=False
    )

    image = forms.FileField(
        label='Фото профиля:',
        widget=forms.FileInput(attrs={'class': 'form-control'}),
        required=False
    )

    class Meta:
        model = Profile
        fields = ('birthday_date', 'gender', 'phone_number', 'image')


class CustomAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        label='Имя пользователя:',
        widget=forms.TextInput(attrs={"autofocus": True,
                                      'class': 'form-control',
                                      }))
    password = forms.CharField(
        label='Пароль:',
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
                                          'class': 'form-control',
                                          }),
    )


class CreateResumeForm(forms.ModelForm):
    position = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': 'Желаемая должность',
                                                             'aria-describedby': "button-addon2",
                                                             }))

    class Meta:
        model = app_resume.models.Resume
        fields = ('position',)


class PrimaryResumeSelectForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        instance = kwargs.pop('instance', None)
        super(PrimaryResumeSelectForm, self).__init__(*args, **kwargs)
        self.fields['is_primary'].queryset = \
            app_resume.models.Resume.objects.filter(user=self.user)

        if instance:
            self.fields['is_primary'].initial = instance

    is_primary = forms.ModelChoiceField(
        queryset=None,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input ms-auto',
                                        'value': '',
                                        'onclick': 'javascript: submit()'}),
    )

    class Meta:
        model = app_resume.models.Resume
        fields = ['is_primary']


class SocialLinksForm(forms.ModelForm):
    twitter = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    facebook = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    linked_in = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    vk = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    instagram = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    hh = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    git_hub = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    class Meta:
        model = SocialLinks
        fields = ['twitter', 'facebook', 'linked_in', 'vk', 'instagram', 'hh', 'git_hub']

templates/app_users/create_profile.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
  {% include 'blocks/navigation/breadcrumbs.html' %}
  {% block main_content %}

    <div class="container">
      {% include 'blocks/page_header.html' with path_name='create_profile' %}
      {% include 'blocks/forms/form.html' with path_name='create_profile' submit_text='Отправить' %}
    </div>

  {% endblock %}

{% endblock %}

templates/app_users/login.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
  {% include 'blocks/navigation/breadcrumbs.html' %}
  {% block main_content %}

    <div class="container">
      {% include 'blocks/page_header.html' with path_name='login' %}
      {% include 'blocks/forms/form.html' with path_name='login' submit_text='Войти' %}
    </div>

  {% endblock %}

{% endblock %}

templates/app_users/profile.html
{% extends 'base.html' %}

{% load djutils %}
{% load app_users_filters %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
  {% include 'blocks/navigation/breadcrumbs.html' %}
  {% block main_content %}
    <div class="container">
      {% include 'blocks/page_header.html' with path_name='profile' %}
      <div class="row gx-5">
        <div class="col-lg-5">
          {% include 'blocks/user_card.html' with path_name='profile' object=user %}
        </div>
        <div class="col-md-7">
          <div class="profile-info mb-5">
            {% include 'blocks/second_title.html' with title='Данные профиля' %}
            <ul class="list-group list-group-flush shadow rounded-2 bg-light mb-3">
              <li class="list-group-item bg-light">
                <label for="id_birth_date" class="form-label">Дата рождения:</label>
                {% if user.profile.birthday_date %}
                  {{ user.profile.birthday_date }}
                {% else %}
                  <p class="text-body-secondary d-inline">Не указано</p>
                {% endif %}
              </li>
              <li class="list-group-item bg-light">
                <label for="id_gender" class="form-label">Пол:</label>
                {{ user.profile.get_gender }}
              </li>
              <li class="list-group-item bg-light">
                <label for="id_phone_number" class="form-label">Телефон:</label>
                {% if user.profile.phone_number %}
                  {{ user.profile.phone_number }}
                {% else %}
                  <p class="text-body-secondary d-inline">Не указан</p>
                {% endif %}
              </li>
            </ul>
            <a href="{% url 'profile_update' %}" class="btn btn-secondary">Редактировать профиль</a>
          </div>
          <div class="resume-list mb-5">
            {% include 'blocks/second_title.html' with title='Ваши резюме' %}
            {% if user.resume_set.all %}
              <form method="post" action="{% url 'resume_is_primary_update' username=user.username %}">
                {% csrf_token %}
                <div class="list-group my-3 shadow" id="resume_list">
                  {% for resume, radio in user.resume_set.all|zip:primary_resume_select_form.is_primary %}
                    <a href="{% url 'resume' username=user.username slug=resume.slug %}"
                       class="list-group-item list-group-item-action
                       {% if resume.is_primary %} active{% else %} bg-light{% endif %}" aria-current="true">
                      <div class="d-sm-flex flex-grow-1 justify-content-between">
                        <h5 class="mb-1">{{ resume.position }}</h5>
                        <div class="d-flex ms-auto">
                          <small class="me-3">updated {{ resume.updated_date | timesince }} ago</small>
                          {{ radio.tag }}
                        </div>
                      </div>
                    </a>
                  {% endfor %}
                </div>
              </form>
            {% else %}
              <p class="ps-3">Вы еще не добавляли резюме, создайте новое резюме сейчас!</p>
            {% endif %}
            <form method="post" id="create_resume_form">
              {% csrf_token %}
              <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                {{ form.position }}
                <button class="btn btn-primary flex-shrink-0" type="submit" id="button-addon2">Создать новое резюме</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

  {% endblock %}

{% endblock %}

templates/app_users/signup.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
  {% include 'blocks/navigation/breadcrumbs.html' %}
  {% block main_content %}

    <div class="container">
      {% include 'blocks/page_header.html' with path_name='signup' %}
      {% include 'blocks/forms/form.html' with path_name='signup' submit_text='Зарегистрироваться' %}
    </div>

  {% endblock %}

{% endblock %}

templates/app_users/user_update.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
  {% include 'blocks/navigation/breadcrumbs.html' %}
  {% block main_content %}

    <div class="container">
      {% include 'blocks/page_header.html' with path_name='user_update' %}
      {% include 'blocks/forms/form.html' with path_name='user_update' submit_text='Отправить' %}
    </div>

  {% endblock %}

{% endblock %}