CV_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from CV_project import settings
from app_resume.views import MainView

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('users/', include('app_users.urls')),
    path('resume/', include('app_resume.urls')),
    path('social/', include('app_social.urls')),
    path('job_hunt', include('app_job_hunt.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_users/urls.py
from django.urls import path

from .views import ProfileView, SignUpView, CreateProfileView, Login, Logout, \
    ProfileUpdateView, UserUpdateView, SocialLinksUpdateView

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('user_update/', UserUpdateView.as_view(), name='user_update'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('create_profile/', CreateProfileView.as_view(), name='create_profile'),
    path('profile_update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('social_links_update/', SocialLinksUpdateView.as_view(), name='social_links_update')
]

app_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User

import app_resume.models
from .models import Profile, SocialLinks

from django.utils.translation import gettext_lazy as _


class SignUpUserForm(UserCreationForm):
    username = forms.CharField(
        label='Логин для входа:',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'aria-describedby': "usernameHelp",
                                      }))

    email = forms.EmailField(
        label='Email:',
        widget=forms.EmailInput(attrs={'class': 'form-control',
                                       'aria-describedby': "emailHelp",
                                       }))

    password1 = forms.CharField(
        label='Пароль:',
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'id': 'password1_field'}))

    password2 = forms.CharField(
        label='Повторите пароль:',
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                          'id': 'password2_field'}))

    first_name = forms.CharField(
        label='Имя:',
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'area-describedby': 'first_nameHelp',
                                      }))

    last_name = forms.CharField(
        label='Фамилия:',
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'area-describedby': 'last_nameHelp',
                                      }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(
        label='Имя пользователя:',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'area-describedby': 'usernameHelp',
                                      }))

    first_name = forms.CharField(
        label='Имя:',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'area-describedby': 'first_nameHelp',
                                      }))

    last_name = forms.CharField(
        label='Фамилия:',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'area-describedby': 'last_nameHelp',
                                      }))

    email = forms.EmailField(
        label='Адрес электронной почты:',
        widget=forms.EmailInput(attrs={'class': 'form-control',
                                       'area-describedby': 'last_nameHelp',
                                       }))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class CreateProfileForm(forms.ModelForm):
    GENDER_CHOICES = (
        ('M', 'Муж'),
        ('F', 'Жен'),
        ('O', 'Другое'),
    )

    birthday_date = forms.DateField(
        label='День вашего рождения:',
        widget=forms.DateInput(attrs={'class': 'form-control',
                                      'type': 'date'}),
        required=False
    )

    gender = forms.CharField(
        label='Пол:',
        widget=forms.Select(attrs={'class': 'form-control'},
                            choices=GENDER_CHOICES),
        required=False
    )

    phone_number = forms.CharField(
        label='Телефон:',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'value': '+7',
                                      'placeholder': '+7'}),
        required=False
    )

    image = forms.FileField(
        label='Фото профиля:',
        widget=forms.FileInput(attrs={'class': 'form-control'}),
        required=False
    )

    class Meta:
        model = Profile
        fields = ('birthday_date', 'gender', 'phone_number', 'image')


class CustomAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        label='Имя пользователя:',
        widget=forms.TextInput(attrs={"autofocus": True,
                                      'class': 'form-control',
                                      }))
    password = forms.CharField(
        label='Пароль:',
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
                                          'class': 'form-control',
                                          }),
    )


class CreateResumeForm(forms.ModelForm):
    position = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': 'Желаемая должность',
                                                             'aria-describedby': "button-addon2",
                                                             }))

    class Meta:
        model = app_resume.models.Resume
        fields = ('position',)


class PrimaryResumeSelectForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        instance = kwargs.pop('instance', None)
        super(PrimaryResumeSelectForm, self).__init__(*args, **kwargs)
        self.fields['is_primary'].queryset = \
            app_resume.models.Resume.objects.filter(user=self.user)

        if instance:
            self.fields['is_primary'].initial = instance

    is_primary = forms.ModelChoiceField(
        queryset=None,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input ms-auto',
                                        'value': '',
                                        'onclick': 'javascript: submit()'}),
    )

    class Meta:
        model = app_resume.models.Resume
        fields = ['is_primary']


class SocialLinksForm(forms.ModelForm):
    twitter = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    facebook = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    linked_in = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    vk = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    instagram = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    hh = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    git_hub = forms.URLField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )

    class Meta:
        model = SocialLinks
        fields = ['twitter', 'facebook', 'linked_in', 'vk', 'instagram', 'hh', 'git_hub']

templates/blocks/forms/field_update_form.html
{% block field_update_form %}

  {% if object == user %}
    <div class="mb-3">
      <form method="post" action="{% url path_name username=user.username slug=resume.slug %}">
        {% csrf_token %}
        {% for field in form %}
          <label class="form-label">{{ field.label }}</label>
          <div class="input-group">
            {{ field }}
            <button type="submit" class="btn btn-light fw-bold border">+</button>
          </div>
        {% endfor %}
      </form>
    </div>
  {% else %}
    <p>Пользователь еще не добавил информацию в этот раздел</p>
  {% endif %}

{% endblock %}

templates/blocks/forms/form.html
{% block form %}

  <form method="post" id="{{ path_name }}_form"
        {% if path_name == 'create_profile' %}enctype="multipart/form-data"{% endif %}
  >
    {% csrf_token %}
    <div class="container p-0">
      <div class="row">
        {% include 'blocks/messages.html' %}
        {% for field in form %}
          <div class="mb-3">
            <label class="form-label">{{ field.label }}</label>
            <div class="col-md-6 col-lg-5">
              {{ field }}
            </div>
            {% include 'blocks/forms/help_fields.html' %}
          </div>
        {% endfor %}
        <div class="col-md-6 col-lg-5 pe-0 mt-3" id="password_repeat_alert" hidden>
          <div class="alert alert-warning" role="alert">
            Введенные пароли не совпадают!
          </div>
        </div>
      </div>
    </div>
    {% include 'blocks/buttons/submit_button.html' %}
  </form>

{% endblock %}

templates/blocks/forms/help_fields.html
{% block help_fields %}

  {% if path_name == 'additional_education_update' %}

    {% if field.name == 'description' %}
      <div id="descriptionHelp" class="form-text">Опишите учебную программу которую вы освоили.</div>
    {% elif field.name == 'website_url' %}
      <div id="website-urlHelp" class="form-text">Вы можете добавить URL ссылку на сайт учебной программы.</div>
    {% elif field.name == 'diploma' %}
      <div id="diplomaHelp" class="form-text">Вы можете загрузить на сайт ваш диплом или сертификат.</div>
    {% endif %}

  {% elif path_name == 'institution_update' %}

    {% if field.name == 'description' %}
      <div id="descriptionHelp" class="form-text">Опишите факультет или специальность которую вы получили.</div>
    {% elif field.name == 'website_url' %}
      <div id="website-urlHelp" class="form-text">Вы можете добавить URL ссылку на сайт учебного учреждения.</div>
    {% elif field.name == 'diploma' %}
      <div id="diplomaHelp" class="form-text">Вы можете загрузить на сайт ваш диплом.</div>
    {% elif field.name == 'is_primary' %}
      <div id="isPrimary" class="form-text">Если сделать элемент главным эта информация будет отображаться на странице поиска.</div>
    {% endif %}

  {% elif path_name == 'electronic_certificate_update' %}

      {% if field.name == 'certificate_url' %}
        <div id="certificate_urlHelp" class="form-text">Прикрепите ссылку на ваш сертификат в интернете.</div>
      {% elif field.name == 'certificate' %}
        <div id="certificateHelp" class="form-text">Вы можете загрузить ваш сертификат на сайт.</div>
      {% elif field.name == 'completion_percentage' %}
        <div id="diplomaHelp" class="form-text">Оценка или процент выполнения курса по шкале от 0 до 100.</div>
      {% endif %}

  {% elif path_name == 'work_exp_section_update' %}

    {% if field.name == 'title' %}
      <div id="titleHelp" class="form-text">
        Заголовок для периода работы. Это может быть название организации или отрасли.
      </div>
    {% endif %}

  {% elif path_name == 'job_update' %}

    {% if field.name == 'description' %}
      <div id="descriptionHelp" class="form-text">Опишите проект или ваши обязанности на должности в компании.</div>
    {% elif field.name == 'project_url' %}
      <div id="project-urlHelp" class="form-text">Вы можете добавить URL ссылку на портфолио или проект над которым вы работали.</div>
    {% elif field.name == 'git_url' %}
      <div id="git-urlHelp" class="form-text">Вы можете добавить URL ссылку на ваш в проект на GitHub.</div>
    {% endif %}

  {% elif path_name == 'resume_about_me_update' or path_name == 'resume_position_update' or path_name == 'resume_soft_skills_update'%}

    {% if field.name == 'about_me' %}
      <div id="positionHelp" class="form-text">Расскажите немного о себе.</div>
    {% elif field.name == 'position' %}
      <div id="positionHelp" class="form-text">Укажите желаемую должность, данная строка служит в качестве заголовка вашего резюме.</div>
    {% elif field.name == 'soft_skills' %}
      <div id="positionHelp" class="form-text">Расскажите о ваших положительных качествах как кандидата на соответсвующую должность.</div>
    {% endif %}

  {% elif path_name == 'create_profile' %}

    {% if field.name == 'birthday_date' %}
      <div id="birthday_dateHelp" class="form-text">Дата рождения используется для расчета вашего возраста в резюме и при восстановлении пароля учетной записи.</div>
    {% elif field.name == 'phone_number' %}
      <div id="phone_numberHelp" class="form-text">Укажите действующим номер телефона, чтобы ваш будущий работодатель смог до вас дозвониться.</div>
    {% endif %}

  {% elif path_name == 'signup' %}

    {% if field.name == 'username' %}
      <div id="usernameHelp" class="form-text">Будет виден другим пользователям. Используйте латинские буквы и цифры</div>
    {% elif field.name == 'email' %}
      <div id="emailHelp" class="form-text">Введите действующий адрес электронной почты.</div>
    {% elif field.name == 'first_name' or field.name == 'last_name'%}
      <div class="form-text">Необязательное поле.</div>
    {% endif %}

  {% endif %}

{% endblock %}

templates/blocks/forms/item_create_form.html
{% block new_create_form %}

  {% if owner == user %}
    {% include 'blocks/messages.html' with resume_page='True' %}
    <form method="post" {% if enctype == 'multipart' %}enctype="multipart/form-data"{% endif %}
          action="
            {% if path_name == 'job_create' %}
              {% url path_name username=user.username slug=resume.slug section=section.pk %}
            {% else %}
              {% url path_name username=user.username slug=resume.slug %}
            {% endif %}
          ">
      {% csrf_token %}
      {% if path_name == 'work_exp_section_create' and resume.workexpsection_set.all %}
        <hr>
      {% endif %}
      <div class="input-group mb-5">
        {% for field in form %}
          {% if field.name == 'image' %}
            <label class="btn btn-outline-secondary d-flex align-items-center" for="id_image">
              <input id="id_image" name="image" type="file" class="d-none">
              <i class="fa-regular fa-image"></i>
            </label>
          {% else %}
            {{ field }}
          {% endif %}
        {% endfor %}
        {% if not form %}
          <span class="input-group-text flex-grow-1">{% include 'blocks/forms/span_text_for_create_form.html' %}</span>
         {% endif %}
        <button class="btn btn-outline-secondary fw-bold" type="submit" id="{{ path_name }}_button">+</button>
      </div>
    </form>
  {% endif %}

{% endblock %}

templates/blocks/forms/span_text_for_create_form.html
{% block span_text_for_create_form %}

  {% if path_name == 'main_education_create' %}
    Указать уровень образования
  {% elif path_name == 'institution_create' %}
    Добавить учебное учреждение
  {% elif path_name == 'additional_education_create' %}
    Добавить образование
  {% elif path_name == 'electronic_certificate_create' %}
    Добавить сертификат
  {% elif path_name == 'job_create' %}
    Добавить место работы
  {% elif path_name == 'work_exp_section_create' %}
    Добавить период работы
  {% endif %}
{% endblock %}