CV_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from CV_project import settings
from app_resume.views import MainView

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('admin/', admin.site.urls),
    path('users/', include('app_users.urls')),
    path('resume/', include('app_resume.urls')),
    path('social/', include('app_social.urls')),
    path('job_hunt', include('app_job_hunt.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_users/urls.py
from django.urls import path

from .views import ProfileView, SignUpView, CreateProfileView, Login, Logout, \
    ProfileUpdateView, UserUpdateView, SocialLinksUpdateView

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('user_update/', UserUpdateView.as_view(), name='user_update'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('create_profile/', CreateProfileView.as_view(), name='create_profile'),
    path('profile_update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('social_links_update/', SocialLinksUpdateView.as_view(), name='social_links_update')
]

app_social/forms.py
from django import forms

from app_social.models import Comment, Post


class CommentForm(forms.ModelForm):
    message = forms.CharField(
        label="Добавить комментарий:",
        widget=forms.Textarea(attrs={'class': 'form-control',
                                     'rows': '3',
                                     'placeholder': "Введите текст комментария",
                                     'id': 'comment_create_input'}),
    )

    class Meta:
        model = Comment
        fields = ['message']


class CommentUpdateForm(forms.ModelForm):
    message = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={'class': 'form-control',
                                     'rows': '3',
                                     'placeholder': "Введите текст комментария"}),
    )

    class Meta:
        model = Comment
        fields = ['message']


class PostCreateForm(forms.Form):
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control',
                                     'aria-describedby': 'messageHelp',
                                     'placeholder': 'Что у вас нового? Добавьте сообщение в блог!',
                                     'rows': '3'}),
    )

    image = forms.FileField(
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control'}),
    )


class PostForm(forms.ModelForm):
    message = forms.CharField(
        required=True,
        label='Введите текст сообщения:',
        widget=forms.Textarea(attrs={'class': 'form-control simple-mde-enable',
                                     'aria-describedby': 'messageHelp',
                                     'rows': '8'}),
    )

    image = forms.FileField(
        required=False,
        label='Прикрепите изображение:',
        widget=forms.FileInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = Post
        fields = ['message', 'image']


class ResumeSearchForm(forms.Form):
    search_query = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-control",
                                      'placeholder': "Найти...",
                                      'aria-label': "Search"})
    )

templates/blocks/comment_item.html
{% load djutils %}

{% block comment_item %}

  <li class="list-group-item">
    <div class="comment-item mt-2">
      {% if comment.user %}
        <a href="{% url 'primary_resume' username=comment.user.username %}" class="text-uppercase mb-1">{{ comment.user.username }}</a>
      {% else %}
        <p class="text-uppercase mb-1 text-body-secondary">Аноним</p>
      {% endif %}
      <p class="comment-text">{{ comment.message }}</p>
      <form method="post" action="{% url 'comment_update' pk=comment.pk %}"
            style="display: none;" class="edit-form">
        {% csrf_token %}
        <div class="">
          {{ comment_edit_forms|get_value_from_dict:comment.pk }}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary btn-sm mt-1">Сохранить</button>
          </div>
        </div>
      </form>
      <div class="item-footer container p-0">
        <div class="row">
          <div class="comment-info-block col-sm-8 mt-2">
            <small class="">{{ comment.created_date  | date:'d.m.Y G:i' }}</small>
            <br>
            {% if comment.updated_date != comment.created_date %}
              <small class="align-self-center">Отредактировано: {{ comment.updated_date | date:'d.m.Y G:i' }}</small>
            {% endif %}
          </div>
          <div class="comment-buttons-block d-flex align-items-end justify-content-end col-sm-4 mt-2">
            {% include 'blocks/buttons/edit_button.html' with owner=comment.user prefix='edit-comment-' id=comment.pk %}
            {% include 'blocks/buttons/delete_button.html' with path_name='comment_delete' pk=comment.pk owner=comment.user %}
            {% include 'blocks/buttons/like_button.html' with uuid_key=comment.pk %}
          </div>
        </div>
      </div>
    </div>
  </li>

{% endblock %}

templates/blocks/comments_modal.html
{% load djutils %}

{% block comments_modal %}

  <div class="modal fade" id="comments-{{ uuid_key }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        {% if delete_path_name != 'job_delete' %}
          <div class="m-1">
            <ul class="content-item p-0">
              {% if content_type == 'resume' %}
                {% include 'blocks/objects/resume_object.html' with modal='comment' %}
              {% else %}
                {% include 'app_resume/blocks/item.html' with modal='comments' %}
              {% endif %}
            </ul>
          </div>
        {% endif %}
        <div class="modal-header">
          <h1 class="modal-title fs-5 d-block" id="exampleModalLabel">Комментарии</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <ul class="list-group list-group-flush mb-4">
            {% if not comments|get_value_from_dict:uuid_key %}
              <p>Комментариев пока нет, но вы можете оставить свой!</p>
            {% endif %}
            {% for comment in comments|get_value_from_dict:uuid_key %}
              {% include 'blocks/comment_item.html' %}
            {% endfor %}
            {% include 'blocks/messages.html' with path_name='comment_create' %}
          </ul>
          <form method="post" action="{% url 'comment_create' pk=uuid_key %}">
            {% csrf_token %}
            <label for="id_message" class="form-label">Добавить комментарий:</label>
            <div class="input-group">
              {{ comment_form.message }}
              <button type="submit" class="btn btn-secondary fw-bold">+</button>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/blocks/messages.html
{% block messages %}

  {% if messages or form.errors %}
    <div class="{% if not resume_page and not modal %}
        messages-block col-md-6 col-lg-5{% endif %} mt-3">
      {% for message in messages %}
        {% if path_name in message.tags or message.tags|wordcount == 1 %}
          <div class="alert {% if message.tags %}{{ message.tags }}{% else %}alert-warning{% endif %}" role="alert">
            {{ message|safe }}
          </div>
        {% endif %}
      {% endfor %}
      {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ field.label }}</strong> {{ error|escape }}
                </div>
            {% endfor %}
        {% endfor %}
      {% endif %}
    </div>
  {% endif %}

{% endblock %}

templates/blocks/no_objects_message.html
{% block no_objects_message %}

  <p class="text-body-secondary">Пользователь еще не добавил информацию в этот раздел</p>

{% endblock %}

templates/blocks/page_header.html
{% block page_header %}

  <div id="page_header" class="row mb-4">
    <div class="col-12">
      <h1>{{ title }}</h1>
      <p>
        {% if user.is_authenticated and user.first_name %}
          Привет, {{ user.first_name }}!
        {% elif user.is_authenticated %}
          Привет, {{ user.username }}!
        {% endif %}
        {% if path_name == 'resume_list' %}
          На этой странице вы можете посмотреть резюме других пользователей.
          Они располагаются в порядке их рейтинга. Рейтинг можно увеличить
          добавив больше данных в ваше резюме, а также за лайки и комментарии.
        {% elif path_name == 'profile' %}
          На этой странице вы можете посмотреть данные своего профиля.
          Они используются при формировании резюме и для связи с работодателем.
        {% elif path_name == 'create_profile' %}
          Перед тем как перейти к созданию резюме, расскажите немного о себе.
        {% elif path_name == 'login' %}
          Используйте свой логин и пароль, чтобы авторизоваться на сайте.
        {% elif path_name == 'signup' %}
          Зарегистрируйтесь, чтобы иметь возможность составить свое резюме и оставлять комментарии.
        {% elif path_name == 'user_update' %}
          Вы можете изменить имя пользователя, адрес электронной почты или личные данные.
        {% elif path_name == 'post_list' %}
          На этой странице представлены
          {% if author == user %}ваши новости.
          {% elif author%}новости пользователя {{ author.first_name|title }}.
          {% else %}новости других пользователей.{% endif %}
          Посты отображаются в хронологическом порядке. Вы можете оставлять комментарии и лайки,
          чтобы поддержать общение и обмен мнениями в сообществе.
        {% elif path_name == '404' %}
          Кажется такой страницы пока не существует.
        {% endif %}
      </p>
    </div>
  </div>

{% endblock %}

templates/blocks/prime_title.html
{% block resume_prime_title %}

  <h2 class="text-uppercase"><i class="fa-solid {{ icon }} title-icon fs-1 me-3 mb-1"></i>{{ title }}</h2>

{% endblock %}

templates/blocks/second_title.html
{% block resume_second_title %}

  <h3 class="text-uppercase fs-5">
    {% if icon %}
      <i class="fa-solid {{ icon }} fs-3 title-icon me-2 mb-1"></i>
    {% endif %}
    {{ title }}
  </h3>

{% endblock %}

templates/blocks/skill_list.html
{% load app_resume_filters %}

{% block skill_list %}

  {% for object in object_set %}
    <button class="btn btn-light position-relative mb-3 me-3 shadow-sm skill-item item {% if path_name == 'resume_list' %}btn-sm{% endif %}"
            type="button" id="{{ object.pk }}" {% if path_name == 'resume_list' %}disabled{% endif %}>
      {{ object.title }}
      {% if owner == user %}
        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-secondary hidden-buttons-block close-skill-badge">
          <i class="fa-solid fa-xmark"></i>
          <span class="visually-hidden">unread messages</span>
        </span>
      {% endif %}
      <span class="position-absolute top-100 start-100 translate-middle badge rounded-pill bg-secondary hidden-buttons-block like-skill-badge"
            id="like-{{ object.pk }}">
        <i class="fa-heart
          {% if object.pk in users_likes_uuid %}
            fa-solid">
          {% else %}
            fa-regular">
          {% endif %}
        </i>
        <small>
          {% if like_counts|get_value_from_dict:object.pk %}
            {{ like_counts|get_value_from_dict:object.pk }}
          {% else %}
            0
          {% endif %}
        </small>
      </span>
    </button>
    {% include 'blocks/comments_modal.html' with uuid_key=object.pk type_content='skill' %}
  {% endfor %}

{% endblock %}

templates/blocks/social_links_block.html
{% block social_links %}

  <div class="sharebuttons btn-group btn-group-lg btn-group-justified">
    {% include 'blocks/social_links_item.html' with url=owner.profile.sociallinks.twitter service_name='twitter' icon='fa-twitter' form=social_links_form.twitter %}
    {% include 'blocks/social_links_item.html' with url=owner.profile.sociallinks.facebook service_name='facebook' icon='fa-facebook-f' form=social_links_form.facebook %}
    {% include 'blocks/social_links_item.html' with url=owner.profile.sociallinks.instagram service_name='instagram' icon='fa-instagram' form=social_links_form.instagram %}
    {% include 'blocks/social_links_item.html' with url=owner.profile.sociallinks.linked_in service_name='linkedin' icon='fa-linkedin-in' form=social_links_form.linked_in %}
    {% include 'blocks/social_links_item.html' with url=owner.profile.sociallinks.vk service_name='vk' icon='fa-vk' form=social_links_form.vk %}
    {% include 'blocks/social_links_item.html' with url=owner.profile.sociallinks.git_hub service_name='github' icon='fa-github' form=social_links_form.git_hub %}
  </div>

{% endblock %}

templates/blocks/social_links_item.html
{% block social_links_item %}

  {% if url %}
    <a class="btn text-white {{ service_name }}" href="{{ url }}"
       role="button" target="_blank" rel="noopener noreferrer">
      <i class="fab {{ icon }}"></i>
    </a>
  {% elif owner == user %}
    <button type="button" class="btn text-white social-link {{ service_name }}"
            data-bs-html="true"
            data-bs-placement="bottom"
            data-bs-custom-class="shadow"
            data-bs-toggle="popover"
            data-bs-title="Ваш профиль в {{ service_name|title }}"
            data-bs-content=
                    '<form method="post" action="{% url 'social_links_update' %}">
                       {% csrf_token %}
                         <div class="d-flex">
                         {{ form }}
                         <button name="twitter-submit" class="btn btn-outline-secondary fw-bold ms-2" type="submit">+</button>
                       </div>
                     </form>'
    >
      <i class="fab {{ icon }} social-logo"></i>
      <i class="fw-bold social-plus-sign">+</i>
    </button>
  {% endif %}

{% endblock %}

templates/blocks/update_modal.html
{% load djutils %}

{% block update_modal %}

  {% if owner == user %}
    <div class="modal fade" id="{{ prefix }}{{ object.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          {% if path_name == 'institution_update' or path_name == 'additional_education_update' or path_name == 'electronic_certificate_update' %}
            <div class="m-1">
              <ul class="content-item p-0">
                {% include 'app_resume/blocks/item.html' with modal='update'%}
              </ul>
            </div>
          {% endif %}
          <form method="post" action="
              {% if path_name == 'job_update' %}
                {% url path_name username=user.username slug=resume.slug section=object.work_exp_section.pk pk=object.pk %}
              {% elif path_name == 'resume_about_me_update' or path_name == 'resume_position_update' or path_name == 'resume_soft_skills_update' %}
                {% url path_name username=user.username slug=resume.slug %}
              {% else %}
                {% url path_name username=user.username slug=resume.slug pk=object.pk %}
              {% endif %}
          ">
            {% csrf_token %}
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Редактировать</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              {% for field in form %}
                <div class="mb-3">
                  <label class="form-label">{{ field.label }}</label>
                  {% if path_name == 'electronic_certificate_update' and field.name == 'completion_percentage' %}
                    <div class="mb-3 d-flex align-items-center">
                      {{ field }}
                      <span class="input-group-text ms-3">
                        <output id="range_value_{{ certificate.pk }}" class="completion-percentage-value"></output>
                      </span>
                    </div>
                  {% else %}
                    {{ field }}
                  {% endif %}
                  {% include 'blocks/forms/help_fields.html' with path_name=path_name %}
                </div>
              {% endfor %}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
              <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  {% endif %}

{% endblock %}

templates/blocks/user_card.html
{% block user_card %}

  <div class="user-card rounded-3 bg-light bg-gradient pt-5 pb-1 px-3 mb-5 shadow">
    <div class="hero {% if path_name == 'resume' %}mb-4{% else %}mb-5{% endif %}">
      {% if object.profile.image %}
        <div class="avatar-container mx-auto mb-3 d-block" style="height: 250px; width: 250px">
          <img src="{{ object.profile.image.url }}" class="avatar rounded-circle w-100 h-auto shadow" alt="user`s avatar"
               style="object-fit: cover; aspect-ratio: 1 / 1;">
        </div>
      {% else %}
        <div class="rounded-circle bg-secondary mx-auto d-flex align-items-center mb-3 shadow" style="height: 250px; width: 250px">
          {% if object == user %}
            <p class="mx-auto text-light">Здесь будет ваше фото</p>
          {% else %}
            <p class="mx-auto text-light">{{ object.username }}</p>
          {% endif %}
        </div>
      {% endif %}
      {% if object.first_name or object.last_name %}
        <h1 class="text-uppercase text-center">
          {{ object.first_name }}
          <br>
          <strong>{{ object.last_name }}</strong>
        </h1>
      {% elif object == user %}
        <p class="text-center">
          Вы не указали ваше имя или фамилию
          <br>
          <a href="{% url 'user_update' %}?next={{ request.path }}">Редактировать</a>
        </p>
      {% else %}
        <h1 class="text-uppercase text-center">
          {{ object.username }}
        </h1>
      {% endif %}
      {% if path_name == 'resume' %}
        <div class="resume-position-item d-flex justify-content-center">
          <p class="text-uppercase text-center lead my-0"><strong>{{ resume.position }}</strong></p>
          {% include 'blocks/buttons/edit_button.html' with prefix='position-update-' id=resume.pk %}
        </div>
        <!-- Modal -->
        {% include 'blocks/modals/update_modal.html' with path_name='resume_update' prefix='position-update-' object=resume form=resume_position_form %}
      {% endif %}
    </div>
    {% if path_name == 'resume' %}
      <div class="about-me item">
        {% if resume.about_me %}
          <div class="resume-about-me-item mb-4">
            <p class="my-0">{{ resume.about_me }}</p>
            <div class="item-footer d-flex justify-content-end">
              {% include 'blocks/buttons/edit_button.html' with prefix='about-me-update-' id=resume.pk %}
            </div>
          </div>
          <!-- Modal -->
          {% include 'blocks/modals/update_modal.html' with path_name='resume_update' prefix='about-me-update-' object=resume form=resume_about_me_form %}
        {% else %}
          {% include 'blocks/forms/field_update_form.html' with path_name='resume_update' form=resume_about_me_form %}
        {% endif %}
      </div>
    {% endif %}
    <div class="my-contacts mb-4">
      {% if path_name == 'resume' %}
        {% include 'blocks/second_title.html' with icon='fa-address-book' title='Контакты' %}
      {% endif %}
      <ul class="list-unstyled">
        {% if path_name == 'profile' %}
          <li class="list-group-item mb-1">
            <p class="me-3 d-inline">Имя пользователя:</p><p class="d-inline">{{ object.username }}</p>
          </li>
        {% endif %}
        <li class="list-group-item mb-1">
          <p class="me-3 d-inline">Email:</p><a href="mailto:{{ object.email }}">{{ object.email }}</a>
        </li>
        <li class="list-group-item mb-3">
          <p class="me-3 d-inline">Телефон:</p>
          {% if object.profile.phone_number %}
            <a href="tel:{{ object.profile.phone_number }}">{{ object.profile.phone_number }}</a>
          {% else %}
            <p class="d-inline">Не указан</p>
          {% endif %}
        </li>
        <li class="list-group-item mb-3">
          {% include 'blocks/social_links_block.html' %}
        </li>
      </ul>
    </div>
    {% if path_name == 'resume' %}
      <div class="personal-qualities mb-4 item">
        {% include 'blocks/second_title.html' with icon='fa-circle-check' title='Личные качества' %}
        {% if resume.soft_skills %}
          <div class="resume-soft-skills-item">
            <p class="my-0">{{ resume.soft_skills }}</p>
            <div class="item-footer d-flex justify-content-end">
              {% include 'blocks/buttons/edit_button.html' with prefix='soft-skills-update-' id=resume.pk %}
            </div>
          </div>
          <!-- Modal -->
          {% include 'blocks/modals/update_modal.html' with path_name='resume_update' prefix='soft-skills-update-' object=resume form=resume_soft_skills_form %}
        {% else %}
          {% include 'blocks/forms/field_update_form.html' with path_name='resume_update' form=resume_soft_skills_form %}
        {% endif %}
      </div>
    {% endif %}
    {% if path_name == 'profile' %}
      <a href="{% url 'user_update' %}" class="text-end d-block mb-2" id="user_update_link" ><small>Редактировать</small></a>
    {% endif %}
  </div>

{%  endblock %}